---
queue: aspect-devx-service
bazel:
  rcfiles:
      - ".aspect/bazelrc/ci.bazelrc"

tasks:
  - build:
      targets:
          - //...
          - -//tools:compdb  # Exclude: com_grail_bazel_compdb is incompatible with current toolchain
      bazel:
        flags:
          - "--config=ci"
  - test:
      targets:
          - //test
      bazel:
        flags:
          - "--config=ci"
  - finalization:

